language: node_js
node_js:
 - "node"
addons:
  apt:
    packages:
      # Dependencia de cypress
      - libgconf-2-4
cache:
  npm: true
  directories:
    # Para cypress
    - ~/.cache

script:
  - npm run test:unit
  - npm run test:e2e-ci
  - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
